{% if theme.passage_end_tag.enabled %}
<div style="text-align:center;color: #ccc;font-size:14px;">
------ 本文结束 ------</div>
<br/>
<div style="border: 1px solid black">
<div style="margin-left:10px">
<span style="font-weight:blod">版权声明</span>
<br/>
<p style="font-size: 10px;line-height: 30px"><a href="http://www.huangyiblog.com" style="color:#258FC6">xiaohuang's Notes</a> by <a href="http://www.huangyiblog.com" style="color:#258FC6">Cheng Tang</a> is licensed under a <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" style="color:#258FC6">Creative Commons BY-NC-ND 4.0 International License</a>.<br/>
由<a href="http://www.huangyiblog.com" style="color:#258FC6">小黄</a>创作并维护的<a href="http://www.huangyiblog.com" style="color:#258FC6">xiaohuang's Notes</a>博客采用<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" style="color:#258FC6">创作共用保留署名-非商业-禁止演绎4.0国际许可证</a>。<br/>
本文首发于<a href="http://www.huangyiblog.com" style="color:#258FC6">xiaohuang's Notes</a> 博客（ <a href="http://www.huangyiblog.com" style="color:#258FC6">http://www.huangyiblog.com</a> ），版权所有，侵权必究。</p>
</div>
</div>
{% endif %}